service: backend-challenge

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs16.x
  stage: dev

functions:
  hello:
    handler: handler.hello
    events:
     - http:
         path: /
         method: get

  reservation:
    handler: handler.reservation
    events:
     - http:
         path: /reservation
         method: get
