service: backend-challenge

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs16.x
  stage: dev

functions:
  removeReservation:
    handler: handler.removeReservation
    events:
      - http:
          path: removeReservation/{userId}
          method: post
          request:
              parameters:
                paths:
                  userId: true
  reservation:
    handler: handler.reservation
    events:
     - http:
         path: reservation/{userId}
         method: post
         request:
            parameters:
              paths:
                userId: true
